apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-setup-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: externalCert.projectId
        value: {{ .Values.externalCert.projectId }}
      - name: externalCert.fapiPepAS.mtlsCertPrefix
        value: {{ .Values.externalCert.fapiPepAS.mtlsCertPrefix }}
      - name: externalCert.fapiPepRS.mtlsCertPrefix
        value: {{ .Values.externalCert.fapiPepRS.mtlsCertPrefix }}
      - name: externalCert.fapiPepAS.tlsCertPrefix
        value: {{ .Values.externalCert.fapiPepAS.tlsCertPrefix }}
      - name: externalCert.fapiPepRS.tlsCertPrefix
        value: {{ .Values.externalCert.fapiPepRS.tlsCertPrefix }}
      - name: externalCert.testTrustedDirectory.tlsCertPrefix
        value: {{ .Values.externalCert.testTrustedDirectory.tlsCertPrefix }}
      - name: ig.truststore.googleSecretName
        value: {{ .Values.devenvs.fapiPepAS.truststore.googleSecretName }}
      - name: ig.ob.signingkey.googleSecretName
        value: {{ .Values.devenvs.fapiPepAS.ob.signingkey.googleSecretName }}
      - name: environment.sapigType
        value: {{ .Values.environment.sapigType }}
      - name: environment.cloudType
        value: {{ .Values.environment.cloudType }}
      - name: cloud.id
        value: {{ .Values.cloud.id }}
      - name: cloud.key
        value: {{ .Values.cloud.key }}
    path: cluster/certificate
    repoURL: https://github.com/SecureBankingAccessToolkit/sbat-cd
    # SH-ToDo - Revert
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true