---
{{- if eq .Values.environment.sapigType ob }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ig.ob.signingKey.secretName }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store               
  target:
    name: {{ .Values.ig.ob.signingKey.secretName }}
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.ig.ob.signingKey.fileName }}
    remoteRef:
      key: {{ .Values.ig.ob.signingKey.googleSecretName }}
{{ end }}
