---
cloud:
  id: dev-aic-ob-private-id
  key: dev-aic-ob-private-key
environment:
  sapigType: ob
  cloudType: CDK
serviceAccount: default
externalCert:
  projectId: example-project
  fapiPepAS:
    mtlsSecretName: fapi-pep-as-mtls-tls-cert
    mtlsCertPrefix: dev-ob-wac
    tlsSecretName: fapi-pep-as-tls-cert
    tlsCertPrefix: dev
  fapiPepRS:
    mtlsSecretName: fapi-pep-rs-mtls-tls-cert
    mtlsCertPrefix: dev-ob-wac
    tlsSecretName: fapi-pep-rs-tls-cert
    tlsCertPrefix: dev
  testTrustedDirectory:
    tlsSecretName: ttd-tls-cert
    tlsCertPrefix: dev
ig:
  truststore:
    secretName: ig-truststore-pem
    fileName: ig-truststore.pem
    googleSecretName: ig-truststore-pem
  ob:
    signingKey:
      secretName: ig-ob-signing-key
      fileName: ig-ob-signing-key.p12
      googleSecretName: ig-ob-signing-key
rcs:
  signing:
    certPrefix: rcs-signing
    secretName: rcs-signing
testTrustedDirectory:
  fileName: test-trusted-dir-keystore.p12
  secretName: test-trusted-dir-keystore
  googleSecretName: test-trusted-dir-keystore
