apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-setup-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: externalCert.projectId
        value: {{ .Values.externalCert.projectId }}
      - name: externalCert.mtls.certPrefix
        value: {{ .Values.externalCert.mtls.certPrefix }}
      - name: externalCert.sapig.certPrefix
        value: {{ .Values.externalCert.sapig.certPrefix }}
      - name: externalCert.ttd.certPrefix
        value: {{ .Values.externalCert.ttd.certPrefix }}
      - name: ig.truststore.googleSecretName
        value: {{ .Values.ig.truststore.googleSecretName }}
      - name: ig.ob.signingkey.googleSecretName
        value: {{ .Values.ig.ob.signingkey.googleSecretName }}
      - name: environment.sapigType
        value: {{ .Values.environment.sapigType }}
      - name: environment.cloudType
        value: {{ .Values.environment.cloudType }}
      - name: openBankingCert.certPrefix
        value: {{ .Values.openBankingCert.certPrefix }}
    path: cluster/certificate
    repoURL: https://github.com/SecureBankingAccessToolkit/sbat-cd
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true